// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: proto/authorbook.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FindBooksAuthorsClient is the client API for FindBooksAuthors service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FindBooksAuthorsClient interface {
	FindBooksByAuthor(ctx context.Context, in *AuthorRequest, opts ...grpc.CallOption) (*BooksResponseList, error)
	FindAuthorsByBook(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*AuthorsResponseList, error)
}

type findBooksAuthorsClient struct {
	cc grpc.ClientConnInterface
}

func NewFindBooksAuthorsClient(cc grpc.ClientConnInterface) FindBooksAuthorsClient {
	return &findBooksAuthorsClient{cc}
}

func (c *findBooksAuthorsClient) FindBooksByAuthor(ctx context.Context, in *AuthorRequest, opts ...grpc.CallOption) (*BooksResponseList, error) {
	out := new(BooksResponseList)
	err := c.cc.Invoke(ctx, "/api.FindBooksAuthors/FindBooksByAuthor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *findBooksAuthorsClient) FindAuthorsByBook(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*AuthorsResponseList, error) {
	out := new(AuthorsResponseList)
	err := c.cc.Invoke(ctx, "/api.FindBooksAuthors/FindAuthorsByBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FindBooksAuthorsServer is the server API for FindBooksAuthors service.
// All implementations should embed UnimplementedFindBooksAuthorsServer
// for forward compatibility
type FindBooksAuthorsServer interface {
	FindBooksByAuthor(context.Context, *AuthorRequest) (*BooksResponseList, error)
	FindAuthorsByBook(context.Context, *BookRequest) (*AuthorsResponseList, error)
}

// UnimplementedFindBooksAuthorsServer should be embedded to have forward compatible implementations.
type UnimplementedFindBooksAuthorsServer struct {
}

func (UnimplementedFindBooksAuthorsServer) FindBooksByAuthor(context.Context, *AuthorRequest) (*BooksResponseList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindBooksByAuthor not implemented")
}
func (UnimplementedFindBooksAuthorsServer) FindAuthorsByBook(context.Context, *BookRequest) (*AuthorsResponseList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAuthorsByBook not implemented")
}

// UnsafeFindBooksAuthorsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FindBooksAuthorsServer will
// result in compilation errors.
type UnsafeFindBooksAuthorsServer interface {
	mustEmbedUnimplementedFindBooksAuthorsServer()
}

func RegisterFindBooksAuthorsServer(s grpc.ServiceRegistrar, srv FindBooksAuthorsServer) {
	s.RegisterService(&FindBooksAuthors_ServiceDesc, srv)
}

func _FindBooksAuthors_FindBooksByAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FindBooksAuthorsServer).FindBooksByAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.FindBooksAuthors/FindBooksByAuthor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FindBooksAuthorsServer).FindBooksByAuthor(ctx, req.(*AuthorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FindBooksAuthors_FindAuthorsByBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FindBooksAuthorsServer).FindAuthorsByBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.FindBooksAuthors/FindAuthorsByBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FindBooksAuthorsServer).FindAuthorsByBook(ctx, req.(*BookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FindBooksAuthors_ServiceDesc is the grpc.ServiceDesc for FindBooksAuthors service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FindBooksAuthors_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.FindBooksAuthors",
	HandlerType: (*FindBooksAuthorsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindBooksByAuthor",
			Handler:    _FindBooksAuthors_FindBooksByAuthor_Handler,
		},
		{
			MethodName: "FindAuthorsByBook",
			Handler:    _FindBooksAuthors_FindAuthorsByBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/authorbook.proto",
}
